name: Build ROM CN for Peridot
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "Official zip Rom package download address"
        required: true
        default: 'https://bn.d.miui.com/OS1.0.14.0.UNPCNXM/miui_PERIDOT_OS1.0.14.0.UNPCNXM_f31a1bac03_14.0.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximizing the build environment
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Check out repository files
        uses: actions/checkout@main
      - name: Building ROM
        run: |
          sudo bash "$GITHUB_WORKSPACE"/make_CN.sh ${{ github.event.inputs.URL }} $GITHUB_ENV $GITHUB_WORKSPACE
      - name: Processing rom
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          cd "$GITHUB_WORKSPACE"/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/${{ env.rom_name }} ${{ env.rom_name }}
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo -e "版本: ${{ env.os_version }}\n安全补丁版本: ${{ env.security_patch }}\n基线版本: ${{ env.base_line }}" > file.log
      - name: Upload to Github Release
      #  uses: ncipollo/release-action@main
      #  with:
      #    artifacts: ${{ github.workspace }}/GithubRelease/*
      #    name: ${{ env.os_version }}
      #    tag: ${{ env.os_version }}
      #    bodyFile: "${{ github.workspace }}/file.log"
      #    allowUpdates: true
      #    artifactErrorsFailBuild: true

        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ env.os_version }}"
          tag: "${{ env.os_version }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB
